name: Run tests on Linux

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
        
jobs:
  linux:
    strategy:
      matrix:
        element:
          - swift: '5.7'
          - swift: '5.8'
    
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.element.swift }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: swift test
