name: Run tests on macOS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macos:
    strategy:
      matrix:
        element:
          - xcode: '14.2'
            machine: macos-12
            withStaticBigInt: false
          - xcode: '14.3'
            machine: macos-13
            withStaticBigInt: true
            
    runs-on: ${{ matrix.element.machine }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.element.xcode }}.app
      - name: Test
        run: swift test
      - name: Test with StaticBigInt
        if: matrix.element.withStaticBigInt
        run: swift test -Xswiftc -DSBI
