name: Build & Tests
on: [push, pull_request]
jobs:
  macos:
    strategy:
      matrix:
        xcode: ['14.2', '14.3']
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build and Test macOS
        run: xcodebuild test -scheme 'Numberick' -destination "platform=macOS"
      - name: Benchmarks macOS
        run: xcodebuild test -scheme 'Numberick-Benchmarks' -destination "platform=macOS"
      - name: Build and Test iOS Simulator
        run: xcodebuild test -scheme 'Numberick' -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Benchmarks iOS Simulator
        run: xcodebuild test -scheme 'Numberick-Benchmarks' -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Build and Test tvOS Simulator
        run: xcodebuild test -scheme 'Numberick' -destination "platform=tvOS Simulator,name=Apple TV"
      - name: Benchmarks tvOS Simulator
        run: xcodebuild test -scheme 'Numberick-Benchmarks' -destination "platform=tvOS Simulator,name=Apple TV"
      - name: Build and Test watchOS Simulator
        run: xcodebuild test -scheme 'Numberick' -destination "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
      - name: Benchmarks watchOS Simulator
        run: xcodebuild test -scheme 'Numberick-Benchmarks' -destination "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
      - name: CocoaPods Lint
        run: pod lib lint --allow-warnings --fail-fast
  linux:
    strategy:
      matrix:
        swift: ['5.7', '5.8']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: swift test
